spring:
  profiles:
    active: local

  # 404 에러일경우 throw 처리
  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  # JPA 기준으로 테이블 만들지 않음
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false

  # DDL 스크립트 사용하지 않음
  sql:
    init:
      mode: never

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
        logger-level: basic

logging:
  level:
    com:
      spring:
        infrastructure:
          finance:
            feign: DEBUG

external-api:
  stock:
    yahoo: https://query1.finance.yahoo.com/
